#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
#- {name: 'Maps',     url: 'blog'}
- {name: 'About',    url: 'about'}

#-------------------------------
# Projects Section

projects:
- {name: 'Art',   url: 'proj-1'}
- {name: 'Writing',   url: 'proj-2'}
- {name: 'Scholarship', url: 'proj-3'}
- {name: 'Game Design',  url: 'proj-4'}
- {name: 'Institutional Change Guide',  url: 'proj-5'}

#-------------------------------
# Contact Section

#social:
#- {icon: 'twitter',   link: 'https://twitter.com/paululele'}
#- {icon: 'github',    link: 'https://github.com/lenpaul'}
#- {icon: 'envelope',  link: 'mailto:mailto:example@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'personal site'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
